### ISSUE TITLE
No module named BeautifulSoup

### ISSUE THREAD

**Issue by wongwm088** [dcrystalj/kindle4rss#1]
pi@raspberrypi:~ $ python kindle4rss.py
Traceback (most recent call last):
  File "kindle4rss.py", line 5, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
pi@raspberrypi:~ $

**Comment by dcrystalj** [comment]
you are missin library...

install pip
and then run `sudo pip install BeautifulSoup`

**Comment by wongwm088** [comment]
Still error

pi@raspberrypi:~ $ sudo python kindle4rss.py
Traceback (most recent call last):
  File "kindle4rss.py", line 4, in <module>
    import urllib, urllib2
ImportError: No module named 'urllib2'

Thank you for your help

**Comment by dcrystalj** [comment]
install urllib2 as well?

`sudo pip install urllib2`
